### ISSUE TITLE
Incorrectly indented YAML should produce an error rather than truncate a section

### ISSUE THREAD

**Issue by mbof** [mbof/hxsync#83]
Repro steps:
1. Load YAML editor for some DAT file
2. Replace the YAML config by
    ```
    - individual_directory:
        - A: "111111111"
       - B: "222222222"
        - C: "333333333"
        - D: "444444444"

    - group_directory:
        - A: "111111111"
        - B: "222222222"
        - C: "333333333"
        - D: "444444444"
    ```

Observed:
 - Diagnostic says "Individual directory: 1 used, 99 left.Group directory: 4 used, 16 left."
 - After saving, the individual directory section is truncated to include just the first entry.

Expected:
 - Error due to bad indentation at line 3.
